### PR TITLE
Fix index page

### PR DESCRIPTION
**Pull request by ghost**
cc @danimo

### CODE REVIEW

**Comment by ghost** [comment]
Maybe also @PVince81 as this currently looks quite ugly on https://doc.owncloud.org

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@danimo how can we bring this online? THX

**Comment by ghost** [comment]
@DeepDiver1975 I think its automatically published. At least the index page on https://doc.owncloud.org/ is already fixed.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I think its automatically published. At least the index page on https://doc.owncloud.org/ is already fixed.

indeed :tada:

**Pull request merged**
